# Generated by Django 3.1.2 on 2020-12-01 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=30, null=True)),
                ('honorarios', models.FloatField(max_length=30, null=True)),
                ('punitorios', models.FloatField(max_length=30, null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_egreso', models.DateField(null=True)),
                ('fecha_rescisión', models.DateField(null=True)),
                ('tipo_contrato', models.CharField(max_length=30, null=True)),
                ('gastos', models.FloatField(null=True)),
                ('servicios', models.CharField(blank=True, max_length=30, null=True)),
                ('vencimiento_pago', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('DNI', models.CharField(max_length=30, null=True)),
                ('CUIT', models.IntegerField(null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('dirección', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('cuenta_bancaria', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inquilino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('DNI', models.CharField(max_length=30, null=True)),
                ('CUIT', models.IntegerField(null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('dirección', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('cuenta_bancaria', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='locador',
            name='CUIT',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='locador',
            name='apellido',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locador',
            name='cuenta_bancaria',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locador',
            name='dirección',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locador',
            name='telefono',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='estado',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tipo',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='locador',
            name='DNI',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='locador',
            name='email',
            field=models.EmailField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='locador',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='ubicación',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
