# Generated by Django 3.1.2 on 2020-12-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0002_auto_20201201_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='valor',
            field=models.FloatField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='locador',
            name='nombre',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
