# Generated by Django 3.1.2 on 2020-12-04 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0003_auto_20201204_1158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(max_length=30, null=True)),
                ('honorarios', models.FloatField(max_length=30, null=True)),
                ('punitorios', models.FloatField(blank=True, max_length=30, null=True)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('fecha_egreso', models.DateField(null=True)),
                ('fecha_rescisión', models.DateField(blank=True, null=True)),
                ('tipo_contrato', models.CharField(max_length=30, null=True)),
                ('vencimiento_pago', models.DateField(null=True)),
                ('garante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.garante')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.inquilino')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(max_length=30, null=True)),
                ('honorarios', models.FloatField(max_length=30, null=True)),
                ('punitorios', models.FloatField(blank=True, max_length=30, null=True)),
                ('fecha_pago', models.DateField()),
                ('agua', models.FloatField(blank=True, max_length=30, null=True)),
                ('luz', models.FloatField(blank=True, max_length=30, null=True)),
                ('gas', models.FloatField(blank=True, max_length=30, null=True)),
                ('expensas', models.FloatField(blank=True, max_length=30, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.contrato')),
            ],
        ),
        migrations.DeleteModel(
            name='Alquiler',
        ),
        migrations.AlterField(
            model_name='locador',
            name='nombre',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='locador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.locador'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.propiedad'),
        ),
    ]
