# Generated by Django 3.1.2 on 2020-12-04 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0004_auto_20201204_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('DNI', models.CharField(max_length=30, null=True)),
                ('CUIT', models.IntegerField(null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('dirección', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('cuenta_bancaria', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('estado', models.CharField(max_length=30, null=True)),
                ('fecha', models.DateField()),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.propiedad')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Comprobante_electronico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_comprobante', models.CharField(max_length=30, null=True)),
                ('tipo_de_documento', models.CharField(max_length=30, null=True)),
                ('DNI', models.CharField(max_length=30, null=True)),
                ('CUIT', models.CharField(max_length=30, null=True)),
                ('IVA', models.CharField(max_length=30, null=True)),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.inquilino')),
            ],
        ),
        migrations.CreateModel(
            name='Cierre_de_caja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.FloatField(max_length=30, null=True)),
                ('egreso', models.FloatField(max_length=30, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.inquilino')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.locador')),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=30, null=True)),
                ('descripcion', models.CharField(max_length=100, null=True)),
                ('fecha', models.DateField()),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.inquilino')),
                ('locador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.locador')),
            ],
        ),
    ]
