# Generated by Django 3.1.2 on 2020-12-15 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0005_aviso_cierre_de_caja_comprobante_electronico_proveedor_reporte'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comprobante_electronico',
            old_name='CUIT',
            new_name='CUIL',
        ),
    ]
