# Generated by Django 3.1.2 on 2020-12-16 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0006_auto_20201215_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='ubicación',
            new_name='ubicacion',
        ),
    ]
