# Generated by Django 3.1.2 on 2020-12-22 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modelos', '0007_auto_20201215_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contrato',
            old_name='fecha_rescisión',
            new_name='fecha_rescision',
        ),
        migrations.RenameField(
            model_name='garante',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='inquilino',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='locador',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='dirección',
            new_name='direccion',
        ),
    ]
